# Core Colors
background            #15130b
foreground            #e8e2d4
selection_foreground  #dbc66f
selection_background  #393000
cursor                #dbc66f
cursor_text_color     #15130b

# Regular Colors
color0  #15130b
color1  #ffb4ab
color2  #dbc66f
color3  #a9d0b3
color4  #f8e287
color5  #eee2bc
color6  #d1c6a1
color7  #e8e2d4

# Bright Colors
color8  #3c3930
color9  #ffb4ab
color10 #dbc66f
color11 #a9d0b3
color12 #f8e287
color13 #eee2bc 
color14 #d1c6a1
color15 #e8e2d4
