# Core Colors
background            #1a110e
foreground            #f1dfd9
selection_foreground  #ffb59a
selection_background  #552009
cursor                #ffb59a
cursor_text_color     #1a110e

# Regular Colors
color0  #1a110e
color1  #ffb4ab
color2  #ffb59a
color3  #d5c78e
color4  #ffdbce
color5  #ffdbce
color6  #e7beaf
color7  #f1dfd9

# Bright Colors
color8  #423733
color9  #ffb4ab
color10 #ffb59a
color11 #d5c78e
color12 #ffdbce
color13 #ffdbce 
color14 #e7beaf
color15 #f1dfd9
