# ~/.config/wallust/templates/kitty.conf

foreground       #FF98E6
background       #010509
cursor           #D26CB1

# Black
color0           #02060B
color8           #D74893

# Red
color1           #344254
color9           #344254

# Green
color2           #55263A
color10          #55263A

# Yellow
color3           #7F6D89
color11          #7F6D89

# Blue
color4           #688FAA
color12          #688FAA

# Magenta
color5           #A6417C
color13          #A6417C

# Cyan
color6           #FF68B4
color14          #FF68B4

# White
color7           #FF8CDA
color15          #F7BDE4
