# ~/.config/wallust/templates/kitty.conf

foreground       #FFBC75
background       #040501
cursor           #E4875D

# Black
color0           #060601
color8           #BE6E2E

# Red
color1           #351309
color9           #351309

# Green
color2           #5A5823
color10          #5A5823

# Yellow
color3           #927456
color11          #927456

# Blue
color4           #7E321A
color12          #7E321A

# Magenta
color5           #C85346
color13          #C85346

# Cyan
color6           #E18A48
color14          #E18A48

# White
color7           #FFAF6A
color15          #F7CFAC
