# ~/.config/wallust/templates/kitty.conf

foreground       #49FFFF
background       #03040A
cursor           #27D6ED

# Black
color0           #04060C
color8           #00AFB8

# Red
color1           #03122C
color9           #03122C

# Green
color2           #0C585C
color10          #0C585C

# Yellow
color3           #04498D
color11          #04498D

# Blue
color4           #0A88FF
color12          #0A88FF

# Magenta
color5           #06AEDB
color13          #06AEDB

# Cyan
color6           #02EFF9
color14          #02EFF9

# White
color7           #3EFFFF
color15          #96F7F7
