# GENERAL
general {
  no_fade_in = true
  grace = 0
  disable_loading_bar = false
  hide_cursor = true
  ignore_empty_input = true
  text_trim = true
}

# BACKGROUND
background {
    monitor = 
    path = $HOME/.config/hypr/current_wallpaper
    blur_passes = 3
    blur_size = 2
    contrast = 0.9
    brightness = 0.8
    vibrancy = 0.3
    noise = 0.035
}




# TIME
label {
    monitor =
    text = $TIME
    color = rgb(ffffff)
    font_size = 120
    font-weight = 1200
    font_family = Helvetica 
    position = 0, 600
    halign = center
    valign = bottom

}




# INPUT FIELD
input-field {
    monitor =
    size = 250, 60
    outline_thickness = 3
    outer_color = rgba(199, 128, 255, 0) 
    dots_size = 0.25
    shadow_passes = 2
    shadow_size = 9
    shadow_color = rgba(0, 0, 0, 0.8)
    rounding = 26
    dots_spacing = 0.35 
    dots_center = true
    font_family = "Red Hat Display"
    inner_color = rgba(255, 255, 255, 0.3) 
    font_color = rgba(255, 255, 255, 1)
    fade_on_empty = true
    placeholder_text = <b>Password here</b>
    hide_input = false
    position = 0, -240
    halign = center
    valign = center
    zindex = 20
}


