# GENERAL
general {
  no_fade_in = true
  grace = 0
  disable_loading_bar = false
  hide_cursor = true
  ignore_empty_input = true
  text_trim = true
}

# BACKGROUND
background {
    monitor = 
    path = ~/Pictures/wallpapers/W39/flowers.jpeg
    blur_passes = 3
    blur_size = 4
    contrast = 0.9
    brightness = 0.8
    vibrancy = 0.3
}




# TIME
label {
    monitor =
    text = $TIME
    # color = rgba(255, 255, 255, 1)
    color = "#FFFFFF"
    font_size = 120
    font-weight = 1200
    font_family = "RedHatDisplay"
    position = 0, 600
    halign = center
    valign = bottom

}

label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %d %B")"
    color = "#FFFFF"
    font_size = 25
    font_family = "RedHatDisplay"
    position = 0, 66
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 250, 60
    outline_thickness = 3
    outer_color = rgba(199, 128, 255, 0) 
    dots_size = 0.25 
    rounding = 18
    dots_spacing = 0.35 
    dots_center = true
    font_family = "RedHatDisplay"
    inner_color = rgba(255, 255, 255, 0.3) 
    font_color = rgba(255, 255, 255, 1)
    fade_on_empty = true
    placeholder_text = <b>Hiii cutieee</b>
    hide_input = false
    position = 0, -240
    halign = center
    valign = center
    zindex = 20
}

label {
    monitor =
    text = hi cutie
    # color = rgba(255, 255, 255, 1)
    color = rgba(255, 255, 255, 1.0)
    font_size = 24
    font_family = "RedHatDisplay"
    position = 0, 1020
    halign = center
    valign = bottom
